language: php

php:
  - 5.4
  - 5.3
 
matrix:
  allow_failures:
    - php: 5.5

before_script:
  - pear channel-discover pear.phix-project.org
  - pear -D auto_discover=1 install -Ba phix/phix4componentdev
  - phing build-vendor

script: phing code-review 
