language: php
php:
  - 5.4
  - 5.3

before_script:
  - apt-get install php5-xdebug
  - apt-get install php5-imagick
  - pear channel-discover pear.phix-project.org
  - pear -D auto_discover=1 install -Ba phix/phix4componentdev
  - phing build-vendor

script: phing code-review 
